const Map<String, Map<String, String>> _strings = {
  'ta': {
    'Settings': 'அமைப்புகள்',
    'Dark Mode': 'இருண்ட பயன்முறை',
    'Language': 'மொழி',
    'English': 'ஆங்கிலம்',
    'Tamil': 'தமிழ்',
    'Hindi': 'இந்தி',
    'Close': 'மூடு',
    'Cancel': 'ரத்துசெய்',
    'Save': 'சேமி',
    'Update': 'புதுப்பி',
    'Delete': 'நீக்கு',
    'Edit': 'திருத்து',
    'Add': 'சேர்',
    'Add Bore': 'போர் சேர்',
    'Add Agent': 'முகவர் சேர்',
    'Add Manager': 'மேலாளரை சேர்',
    'Add Worker': 'தொழிலாளியை சேர்',
    'Add Pipe': 'குழாய் சேர்',
    'Bore Number': 'போர் எண்',
    'Agent Name': 'முகவர் பெயர்',
    'Agent Name (optional)': 'முகவர் பெயர் (விரும்பினால்)',
    'Agent Commission Per Feet': 'அடிக்கு முகவர் கமிஷன்',
    'Agent Commission Per Pipe Foot': 'குழாய் அடிக்கு முகவர் கமிஷன்',
    'Initial Payment': 'ஆரம்ப கட்டணம்',
    'Total Bill': 'மொத்த பில்',
    'Feet Entries': 'அடி உள்ளீடுகள்',
    'PVC Entries': 'பிவிசி உள்ளீடுகள்',
    'Steel Entry': 'எஃகு உள்ளீடு',
    'Feet': 'அடி',
    'Feet (Length)': 'அடி (நீளம்)',
    'Rate/ft': 'வீதம்/அடி',
    'Price / ft': 'விலை / அடி',
    'Price/ft': 'விலை/அடி',
    'Length (ft)': 'நீளம் (அடி)',
    'Size (Qty)': 'அளவு (எண்)',
    'Agent Commission / ft': 'முகவர் கமிஷன் / அடி',
    'Welding Charge': 'வெல்டிங் கட்டணம்',
    'Steel:': 'எஃகு:',
    'Add Feet Entry': 'அடி உள்ளீட்டை சேர்',
    'PVC Entry': 'பிவிசி உள்ளீடு',
    'Steel': 'எஃகு',
    'Agents': 'முகவர்கள்',
    'Bores': 'போர்கள்',
    'Report': 'அறிக்கை',
    'Download Report': 'அறிக்கையை பதிவிறக்கம்',
    'Download Full Report': 'முழு அறிக்கையை பதிவிறக்கம்',
    'Download': 'பதிவிறக்கம்',
    'Share': 'பகிர்',
    'Date': 'தேதி',
    'Amount': 'தொகை',
    'Description': 'விளக்கம்',
    'Name': 'பெயர்',
    'Email': 'மின்னஞ்சல்',
    'Email address': 'மின்னஞ்சல் முகவரி',
    'Email Address': 'மின்னஞ்சல் முகவரி',
    'Enter email': 'மின்னஞ்சலை உள்ளிடுக',
    'Password': 'கடவுச்சொல்',
    'Enter password': 'கடவுச்சொல்லை உள்ளிடுக',
    'Confirm Password': 'கடவுச்சொல்லை உறுதிசெய்',
    'Confirm new password': 'புதிய கடவுச்சொல்லை உறுதிசெய்',
    'New password': 'புதிய கடவுச்சொல்',
    'Enter a new password': 'புதிய கடவுச்சொல்லை உள்ளிடுக',
    'Forgot Password': 'கடவுச்சொல் மறந்துவிட்டது',
    'Forgot Password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'Reset Password': 'கடவுச்சொல்லை மீட்டமை',
    'RESET PASSWORD': 'கடவுச்சொல்லை மீட்டமை',
    'Send Reset Code': 'மீட்டமை குறியீட்டை அனுப்பு',
    'SEND RESET CODE': 'மீட்டமை குறியீட்டை அனுப்பு',
    'Resend OTP': 'OTP ஐ மீண்டும் அனுப்பு',
    'Verify Email': 'மின்னஞ்சலை சரிபார்',
    'Verify OTP': 'OTP ஐ சரிபார்',
    'VERIFY OTP': 'OTP ஐ சரிபார்',
    'Sign In': 'உள்நுழை',
    'SIGN IN': 'உள்நுழை',
    'Sign Up': 'பதிவுசெய்',
    'SIGN UP': 'பதிவுசெய்',
    'SIGN IN WITH GOOGLE': 'Google மூலம் உள்நுழை',
    'SIGN UP WITH GOOGLE': 'Google மூலம் பதிவுசெய்',
    'Continue': 'தொடர்க',
    'CONTINUE': 'தொடர்க',
    'Create Account': 'கணக்கை உருவாக்கு',
    'CREATE ACCOUNT': 'கணக்கை உருவாக்கு',
    'Keep me signed in': 'என்னை உள்நுழைந்த நிலையில் வை',
    "Don't have an account?": 'கணக்கு இல்லையா?',
    'Go to Login': 'உள்நுழைவுக்குச் செல்',
    'Enter your details': 'உங்கள் விவரங்களை உள்ளிடுக',
    'Enter your email and we\'ll send you a reset code': 'உங்கள் மின்னஞ்சலை உள்ளிடுங்கள், மீட்டமை குறியீடு அனுப்பப்படும்',
    'Enter your name': 'உங்கள் பெயரை உள்ளிடுக',
    'Enter your new password': 'உங்கள் புதிய கடவுச்சொல்லை உள்ளிடுக',
    'Enter the complete 6-digit code': 'முழு 6 இலக்க குறியீட்டை உள்ளிடுக',
    'Enter a valid 4-digit PIN': 'சரியான 4 இலக்க PIN ஐ உள்ளிடுக',
    'Enter 4-digit security PIN to confirm settlement': 'தீர்வை உறுதிப்படுத்த 4 இலக்க பாதுகாப்பு PIN ஐ உள்ளிடுக',
    'Enter a valid email': 'சரியான மின்னஞ்சலை உள்ளிடுக',
    'Enter a valid email address': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடுக',
    'Enter a valid amount.': 'சரியான தொகையை உள்ளிடுக.',
    'Enter vehicle number': 'வாகன எண்ணை உள்ளிடுக',
    'Create a password to secure your account': 'உங்கள் கணக்கை பாதுகாக்க கடவுச்சொல்லை உருவாக்குக',
    'Enter SPIN': 'SPIN ஐ உள்ளிடுக',
    'Set SPIN': 'SPIN அமைக்க',
    'SPIN': 'SPIN',
    'SPIN saved!': 'SPIN சேமிக்கப்பட்டது!',
    'Tap to set SPIN': 'SPIN அமைக்க தட்டவும்',
    'Tap to change SPIN': 'SPIN மாற்ற தட்டவும்',
    'Set': 'அமை',
    'Verify': 'சரிபார்',
    'VERIFY': 'சரிபார்',
    'OTP': 'OTP',
    'OR': 'அல்லது',
    'Copied!': 'நகலெடுக்கப்பட்டது!',
    'Copy UPI ID': 'UPI ID ஐ நகலெடு',
    'Pay to': 'செலுத்த வேண்டியவர்',
    'Pay via UPI': 'UPI வழியாக செலுத்து',
    'Pay ₹': '₹ செலுத்து',
    'I\'ve Paid': 'நான் செலுத்தினேன்',
    'Record Payment': 'கட்டணத்தை பதிவுசெய்',
    'Delete Payment': 'கட்டணத்தை நீக்கு',
    'Payments Made': 'செய்த கட்டணங்கள்',
    'This will remove the payment record.': 'இது கட்டண பதிவை நீக்கும்.',
    'Delete Bore': 'போரை நீக்கு',
    'This will remove the bore and related payments.': 'இது போர் மற்றும் தொடர்புடைய கட்டணங்களை நீக்கும்.',
    'Total': 'மொத்தம்',
    'Total Balance:': 'மொத்த இருப்பு:',
    'Total Commission:': 'மொத்த கமிஷன்:',
    'Total Feet': 'மொத்த அடி',
    'Total Amount': 'மொத்த தொகை',
    'Total Income': 'மொத்த வருமானம்',
    'Total Expense': 'மொத்த செலவு',
    'Total Pipe Length': 'மொத்த குழாய் நீளம்',
    'Total Bore Feet': 'மொத்த போர் அடி',
    'Balance': 'இருப்பு',
    'Commission': 'கமிஷன்',
    'Bore Comm.': 'போர் கமிஷன்',
    'Pipe Comm.': 'குழாய் கமிஷன்',
    'Steel Comm.': 'எஃகு கமிஷன்',
    'Settle': 'தீர்வு',
    'Settle Commissions': 'கமிஷன்களை தீர்க்க',
    'Settlement Mode': 'தீர்வு முறை',
    'Settled / Remaining': 'தீர்க்கப்பட்ட / மீதமுள்ள',
    'Insufficient pipe stock for this bore.': 'இந்த போருக்கு போதுமான குழாய் இருப்பு இல்லை.',
    'Owner not linked. Cannot settle.': 'உரிமையாளர் இணைக்கப்படவில்லை. தீர்க்க முடியாது.',
    'No agents added yet.': 'இதுவரை முகவர்கள் யாரும் சேர்க்கப்படவில்லை.',
    'No bores added yet.': 'இதுவரை போர்கள் எதுவும் சேர்க்கப்படவில்லை.',
    'No expenses recorded yet.': 'இதுவரை செலவுகள் எதுவும் பதிவு செய்யப்படவில்லை.',
    'No payments recorded yet.': 'இதுவரை கட்டணங்கள் எதுவும் பதிவு செய்யப்படவில்லை.',
    'No pipes added yet.': 'இதுவரை குழாய்கள் எதுவும் சேர்க்கப்படவில்லை.',
    'No workers added yet.': 'இதுவரை தொழிலாளர்கள் எவரும் சேர்க்கப்படவில்லை.',
    'No workers to generate report': 'அறிக்கை உருவாக்க தொழிலாளர்கள் இல்லை',
    'No manager found with this vehicle number': 'இந்த வாகன எண்ணில் மேலாளர் இல்லை',
    'No manager session found.': 'மேலாளர் அமர்வு இல்லை.',
    'No absent ranges marked yet.': 'இதுவரை விடுப்பு வரம்புகள் குறிக்கப்படவில்லை.',
    'This vehicle number is already used by another manager': 'இந்த வாகன எண் ஏற்கனவே வேறு மேலாளரால் பயன்படுத்தப்படுகிறது',
    'This email already has an account. Please login.': 'இந்த மின்னஞ்சலில் ஏற்கனவே கணக்கு உள்ளது. உள்நுழையவும்.',
    'This date range overlaps with an existing absence': 'இந்த தேதி வரம்பு ஏற்கனவே உள்ள விடுப்புடன் ஒன்றுடன் ஒன்று உள்ளது',
    'This action is permanent. Are you sure?': 'இந்த செயல் நிரந்தரமானது. உறுதியா?',
    'Password reset successfully!': 'கடவுச்சொல் வெற்றிகரமாக மீட்டமைக்கப்பட்டது!',
    'Passwords do not match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'Password must be at least 6 characters': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகளாக இருக்க வேண்டும்',
    'Invalid password': 'தவறான கடவுச்சொல்',
    'Invalid SPIN': 'தவறான SPIN',
    'Manager created!': 'மேலாளர் உருவாக்கப்பட்டார்!',
    'Manager updated!': 'மேலாளர் புதுப்பிக்கப்பட்டார்!',
    'Manager deleted successfully!': 'மேலாளர் வெற்றிகரமாக நீக்கப்பட்டார்!',
    'Manager limit reached. Contact admin to upgrade.': 'மேலாளர் வரம்பு அடைந்தது. மேம்படுத்த நிர்வாகியை தொடர்புகொள்ளவும்.',
    'Manager not found.': 'மேலாளர் இல்லை.',
    'Updated from current manager data': 'தற்போதைய மேலாளர் தரவிலிருந்து புதுப்பிக்கப்பட்டது',
    'Expense': 'செலவு',
    'Expense History': 'செலவு வரலாறு',
    'Expense Management': 'செலவு மேலாண்மை',
    'Save Expense': 'செலவை சேமி',
    'Normal Expense': 'சாதாரண செலவு',
    'Specific Expenses': 'குறிப்பிட்ட செலவுகள்',
    'Delete Expense': 'செலவை நீக்கு',
    'This will remove the expense record.': 'இது செலவு பதிவை நீக்கும்.',
    'Income': 'வருமானம்',
    'Profit/Loss': 'இலாபம்/நஷ்டம்',
    'Average Rate': 'சராசரி வீதம்',
    'Avg. Rate': 'சரா. வீதம்',
    'After all expenses': 'அனைத்து செலவுகளுக்கும் பிறகு',
    'Workers': 'தொழிலாளர்கள்',
    'Worker Attendance': 'தொழிலாளர் வருகை',
    'Worker': 'தொழிலாளி',
    'Delete Worker': 'தொழிலாளியை நீக்கு',
    'Are you sure you want to delete this worker?': 'இந்த தொழிலாளியை நீக்க விரும்புகிறீர்களா?',
    'Edit Worker': 'தொழிலாளியை திருத்து',
    'Mark Absent': 'விடுப்பு குறி',
    'Select absent date range': 'விடுப்பு தேதி வரம்பை தேர்ந்தெடு',
    'Absent Ranges': 'விடுப்பு வரம்புகள்',
    'Monthly Salary': 'மாத சம்பளம்',
    'Monthly Summary': 'மாத சுருக்கம்',
    'Select Worker': 'தொழிலாளியை தேர்ந்தெடு',
    'Select Paid Method': 'கட்டண முறையை தேர்ந்தெடு',
    'Cash': 'பணம்',
    'Account': 'கணக்கு',
    'Select Bore': 'போரை தேர்ந்தெடு',
    'Select From and To Date': 'தொடக்கம் மற்றும் முடிவு தேதியை தேர்ந்தெடு',
    'All days are present automatically. Select a date range only for absent days.': 'அனைத்து நாட்களும் தானாகவே வந்ததாக கருதப்படும். விடுப்பு நாட்களுக்கு மட்டும் தேதி வரம்பை தேர்ந்தெடுக்கவும்.',
    'Attendance': 'வருகை',
    'All time': 'எல்லா நேரமும்',
    'Filter:': 'வடிகட்டி:',
    'Place': 'இடம்',
    'Diesel': 'டீசல்',
    'Tyre': 'டயர்',
    'Labour': 'தொழிலாளர்',
    'Labour Payment': 'தொழிலாளர் கட்டணம்',
    'Basic': 'அடிப்படை',
    'Premium': 'பிரீமியம்',
    'Free': 'இலவசம்',
    'Subscribe': 'சந்தா',
    'Subscription': 'சந்தா',
    'About Subscription': 'சந்தா பற்றி',
    'Choose your plan': 'உங்கள் திட்டத்தை தேர்வுசெய்க',
    'Price per Manager': 'ஒரு மேலாளருக்கான விலை',
    'Managers Allowed': 'அனுமதிக்கப்பட்ட மேலாளர்கள்',
    'Managers': 'மேலாளர்கள்',
    'Manager': 'மேலாளர்',
    'Owner': 'உரிமையாளர்',
    'Owner Dashboard': 'உரிமையாளர் டாஷ்போர்டு',
    'Edit Manager': 'மேலாளரை திருத்து',
    'Delete Manager': 'மேலாளரை நீக்கு',
    'Manager Usage': 'மேலாளர் பயன்பாடு',
    'Live': 'நேரலை',
    'Live Overview': 'நேரலை கண்ணோட்டம்',
    'Active': 'செயலில்',
    'Frozen': 'உறைந்த',
    'Locked': 'பூட்டப்பட்டது',
    'Expired': 'காலாவதி',
    'Not Set': 'அமைக்கப்படவில்லை',
    'Loading...': 'ஏற்றுகிறது...',
    'Loading manager...': 'மேலாளரை ஏற்றுகிறது...',
    'Loading manager data...': 'மேலாளர் தரவை ஏற்றுகிறது...',
    'AQUA TRACK': 'அக்வா டிராக்',
    'BORE DRILLING MANAGEMENT': 'போர் துளையிடல் மேலாண்மை',
    'Tap a manager to view details': 'விவரங்களைக் காண மேலாளரைத் தட்டவும்',
    'Tap + to add your first manager': 'உங்கள் முதல் மேலாளரைச் சேர்க்க + ஐ தட்டவும்',
    'Adjust': 'சரிசெய்',
    'Adjust Quantity': 'அளவை சரிசெய்',
    'New Quantity': 'புதிய அளவு',
    'Quantity': 'அளவு',
    'Used': 'பயன்படுத்தப்பட்டது',
    'Remaining': 'மீதமுள்ளது',
    'Limit': 'வரம்பு',
    'Pipe': 'குழாய்',
    'Pipe in Vehicle': 'வாகனத்தில் உள்ள குழாய்',
    'Pipe Size': 'குழாய் அளவு',
    'Pipes Used:': 'பயன்படுத்தப்பட்ட குழாய்கள்:',
    'Feet Entries:': 'அடி உள்ளீடுகள்:',
    'Details': 'விவரங்கள்',
    'Edit Bore': 'போரைத் திருத்து',
    'Select absent range': 'விடுப்பு வரம்பை தேர்ந்தெடு',
    'Start Date': 'தொடக்க தேதி',
    'End Date': 'முடிவு தேதி',
    'Set Password': 'கடவுச்சொல்லை அமை',
    'January': 'ஜனவரி',
    'February': 'பிப்ரவரி',
    'March': 'மார்ச்',
    'April': 'ஏப்ரல்',
    'May': 'மே',
    'June': 'ஜூன்',
    'July': 'ஜூலை',
    'August': 'ஆகஸ்ட்',
    'September': 'செப்டம்பர்',
    'October': 'அக்டோபர்',
    'November': 'நவம்பர்',
    'December': 'டிசம்பர்',
  },
  'hi': {
    'Settings': 'सेटिंग्स',
    'Dark Mode': 'डार्क मोड',
    'Language': 'भाषा',
    'English': 'अंग्रेज़ी',
    'Tamil': 'तमिल',
    'Hindi': 'हिंदी',
    'Close': 'बंद करें',
    'Cancel': 'रद्द करें',
    'Save': 'सहेजें',
    'Update': 'अपडेट करें',
    'Delete': 'हटाएं',
    'Edit': 'संपादित करें',
    'Add': 'जोड़ें',
    'Add Bore': 'बोर जोड़ें',
    'Add Agent': 'एजेंट जोड़ें',
    'Add Manager': 'प्रबंधक जोड़ें',
    'Add Worker': 'कर्मचारी जोड़ें',
    'Add Pipe': 'पाइप जोड़ें',
    'Bore Number': 'बोर संख्या',
    'Agent Name': 'एजेंट का नाम',
    'Agent Name (optional)': 'एजेंट का नाम (वैकल्पिक)',
    'Agent Commission Per Feet': 'प्रति फुट एजेंट कमीशन',
    'Agent Commission Per Pipe Foot': 'प्रति पाइप फुट एजेंट कमीशन',
    'Initial Payment': 'प्रारंभिक भुगतान',
    'Total Bill': 'कुल बिल',
    'Feet Entries': 'फुट प्रविष्टियां',
    'PVC Entries': 'पीवीसी प्रविष्टियां',
    'Steel Entry': 'स्टील प्रविष्टि',
    'Feet': 'फुट',
    'Feet (Length)': 'फुट (लंबाई)',
    'Rate/ft': 'दर/फुट',
    'Price / ft': 'मूल्य / फुट',
    'Price/ft': 'मूल्य/फुट',
    'Length (ft)': 'लंबाई (फुट)',
    'Size (Qty)': 'आकार (मात्रा)',
    'Agent Commission / ft': 'एजेंट कमीशन / फुट',
    'Welding Charge': 'वेल्डिंग शुल्क',
    'Steel:': 'स्टील:',
    'Add Feet Entry': 'फुट प्रविष्टि जोड़ें',
    'PVC Entry': 'पीवीसी प्रविष्टि',
    'Steel': 'स्टील',
    'Agents': 'एजेंट',
    'Bores': 'बोर',
    'Report': 'रिपोर्ट',
    'Download Report': 'रिपोर्ट डाउनलोड करें',
    'Download Full Report': 'पूरी रिपोर्ट डाउनलोड करें',
    'Download': 'डाउनलोड करें',
    'Share': 'साझा करें',
    'Date': 'तारीख',
    'Amount': 'राशि',
    'Description': 'विवरण',
    'Name': 'नाम',
    'Email': 'ईमेल',
    'Email address': 'ईमेल पता',
    'Email Address': 'ईमेल पता',
    'Enter email': 'ईमेल दर्ज करें',
    'Password': 'पासवर्ड',
    'Enter password': 'पासवर्ड दर्ज करें',
    'Confirm Password': 'पासवर्ड की पुष्टि करें',
    'Confirm new password': 'नए पासवर्ड की पुष्टि करें',
    'New password': 'नया पासवर्ड',
    'Enter a new password': 'नया पासवर्ड दर्ज करें',
    'Forgot Password': 'पासवर्ड भूल गए',
    'Forgot Password?': 'पासवर्ड भूल गए?',
    'Reset Password': 'पासवर्ड रीसेट करें',
    'RESET PASSWORD': 'पासवर्ड रीसेट करें',
    'Send Reset Code': 'रीसेट कोड भेजें',
    'SEND RESET CODE': 'रीसेट कोड भेजें',
    'Resend OTP': 'OTP पुनः भेजें',
    'Verify Email': 'ईमेल सत्यापित करें',
    'Verify OTP': 'OTP सत्यापित करें',
    'VERIFY OTP': 'OTP सत्यापित करें',
    'Sign In': 'साइन इन',
    'SIGN IN': 'साइन इन',
    'Sign Up': 'साइन अप',
    'SIGN UP': 'साइन अप',
    'SIGN IN WITH GOOGLE': 'Google से साइन इन करें',
    'SIGN UP WITH GOOGLE': 'Google से साइन अप करें',
    'Continue': 'जारी रखें',
    'CONTINUE': 'जारी रखें',
    'Create Account': 'खाता बनाएं',
    'CREATE ACCOUNT': 'खाता बनाएं',
    'Keep me signed in': 'मुझे साइन इन रखें',
    "Don't have an account?": 'खाता नहीं है?',
    'Go to Login': 'लॉगिन पर जाएं',
    'Enter your details': 'अपना विवरण दर्ज करें',
    'Enter your email and we\'ll send you a reset code': 'अपना ईमेल दर्ज करें, हम एक रीसेट कोड भेजेंगे',
    'Enter your name': 'अपना नाम दर्ज करें',
    'Enter your new password': 'अपना नया पासवर्ड दर्ज करें',
    'Enter the complete 6-digit code': 'पूरा 6 अंकों का कोड दर्ज करें',
    'Enter a valid 4-digit PIN': 'एक वैध 4 अंकों का PIN दर्ज करें',
    'Enter 4-digit security PIN to confirm settlement': 'निपटान की पुष्टि के लिए 4 अंकों का सुरक्षा PIN दर्ज करें',
    'Enter a valid email': 'एक वैध ईमेल दर्ज करें',
    'Enter a valid email address': 'एक वैध ईमेल पता दर्ज करें',
    'Enter a valid amount.': 'एक वैध राशि दर्ज करें।',
    'Enter vehicle number': 'वाहन नंबर दर्ज करें',
    'Create a password to secure your account': 'अपने खाते को सुरक्षित करने के लिए पासवर्ड बनाएं',
    'Enter SPIN': 'SPIN दर्ज करें',
    'Set SPIN': 'SPIN सेट करें',
    'SPIN': 'SPIN',
    'SPIN saved!': 'SPIN सहेजा गया!',
    'Tap to set SPIN': 'SPIN सेट करने के लिए टैप करें',
    'Tap to change SPIN': 'SPIN बदलने के लिए टैप करें',
    'Set': 'सेट करें',
    'Verify': 'सत्यापित करें',
    'VERIFY': 'सत्यापित करें',
    'OTP': 'OTP',
    'OR': 'या',
    'Copied!': 'कॉपी हो गया!',
    'Copy UPI ID': 'UPI ID कॉपी करें',
    'Pay to': 'भुगतान करें',
    'Pay via UPI': 'UPI से भुगतान करें',
    'Pay ₹': '₹ भुगतान करें',
    'I\'ve Paid': 'मैंने भुगतान कर दिया',
    'Record Payment': 'भुगतान रिकॉर्ड करें',
    'Delete Payment': 'भुगतान हटाएं',
    'Payments Made': 'किए गए भुगतान',
    'This will remove the payment record.': 'इससे भुगतान रिकॉर्ड हट जाएगा।',
    'Delete Bore': 'बोर हटाएं',
    'This will remove the bore and related payments.': 'इससे बोर और संबंधित भुगतान हट जाएंगे।',
    'Total': 'कुल',
    'Total Balance:': 'कुल शेष:',
    'Total Commission:': 'कुल कमीशन:',
    'Total Feet': 'कुल फुट',
    'Total Amount': 'कुल राशि',
    'Total Income': 'कुल आय',
    'Total Expense': 'कुल व्यय',
    'Total Pipe Length': 'कुल पाइप लंबाई',
    'Total Bore Feet': 'कुल बोर फुट',
    'Balance': 'शेष',
    'Commission': 'कमीशन',
    'Bore Comm.': 'बोर कमी.',
    'Pipe Comm.': 'पाइप कमी.',
    'Steel Comm.': 'स्टील कमी.',
    'Settle': 'निपटान',
    'Settle Commissions': 'कमीशन का निपटान',
    'Settlement Mode': 'निपटान मोड',
    'Settled / Remaining': 'निपटाया गया / शेष',
    'Insufficient pipe stock for this bore.': 'इस बोर के लिए अपर्याप्त पाइप स्टॉक।',
    'Owner not linked. Cannot settle.': 'मालिक लिंक नहीं है। निपटान नहीं किया जा सकता।',
    'No agents added yet.': 'अभी तक कोई एजेंट नहीं जोड़ा गया।',
    'No bores added yet.': 'अभी तक कोई बोर नहीं जोड़ा गया।',
    'No expenses recorded yet.': 'अभी तक कोई खर्च दर्ज नहीं किया गया।',
    'No payments recorded yet.': 'अभी तक कोई भुगतान दर्ज नहीं किया गया।',
    'No pipes added yet.': 'अभी तक कोई पाइप नहीं जोड़ा गया।',
    'No workers added yet.': 'अभी तक कोई कर्मचारी नहीं जोड़ा गया।',
    'No workers to generate report': 'रिपोर्ट बनाने के लिए कोई कर्मचारी नहीं',
    'No manager found with this vehicle number': 'इस वाहन नंबर के साथ कोई प्रबंधक नहीं मिला',
    'No manager session found.': 'कोई प्रबंधक सत्र नहीं मिला।',
    'No absent ranges marked yet.': 'अभी तक कोई अनुपस्थिति अवधि चिह्नित नहीं की गई।',
    'This vehicle number is already used by another manager': 'यह वाहन नंबर पहले से किसी अन्य प्रबंधक द्वारा उपयोग किया जा रहा है',
    'This email already has an account. Please login.': 'इस ईमेल पर पहले से खाता है। कृपया लॉगिन करें।',
    'This date range overlaps with an existing absence': 'यह तिथि सीमा मौजूदा अनुपस्थिति से ओवरलैप होती है',
    'This action is permanent. Are you sure?': 'यह कार्रवाई स्थायी है। क्या आपको यकीन है?',
    'Password reset successfully!': 'पासवर्ड सफलतापूर्वक रीसेट हुआ!',
    'Passwords do not match': 'पासवर्ड मेल नहीं खाते',
    'Password must be at least 6 characters': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'Invalid password': 'अमान्य पासवर्ड',
    'Invalid SPIN': 'अमान्य SPIN',
    'Manager created!': 'प्रबंधक बनाया गया!',
    'Manager updated!': 'प्रबंधक अपडेट किया गया!',
    'Manager deleted successfully!': 'प्रबंधक सफलतापूर्वक हटाया गया!',
    'Manager limit reached. Contact admin to upgrade.': 'प्रबंधक सीमा पूरी हो गई। अपग्रेड के लिए व्यवस्थापक से संपर्क करें।',
    'Manager not found.': 'प्रबंधक नहीं मिला।',
    'Updated from current manager data': 'वर्तमान प्रबंधक डेटा से अपडेट किया गया',
    'Expense': 'व्यय',
    'Expense History': 'व्यय इतिहास',
    'Expense Management': 'व्यय प्रबंधन',
    'Save Expense': 'व्यय सहेजें',
    'Normal Expense': 'सामान्य व्यय',
    'Specific Expenses': 'विशिष्ट व्यय',
    'Delete Expense': 'व्यय हटाएं',
    'This will remove the expense record.': 'इससे व्यय रिकॉर्ड हट जाएगा।',
    'Income': 'आय',
    'Profit/Loss': 'लाभ/हानि',
    'Average Rate': 'औसत दर',
    'Avg. Rate': 'औस. दर',
    'After all expenses': 'सभी खर्चों के बाद',
    'Workers': 'कर्मचारी',
    'Worker Attendance': 'कर्मचारी उपस्थिति',
    'Worker': 'कर्मचारी',
    'Delete Worker': 'कर्मचारी हटाएं',
    'Are you sure you want to delete this worker?': 'क्या आप इस कर्मचारी को हटाना चाहते हैं?',
    'Edit Worker': 'कर्मचारी संपादित करें',
    'Mark Absent': 'अनुपस्थित चिह्नित करें',
    'Select absent date range': 'अनुपस्थिति तिथि सीमा चुनें',
    'Absent Ranges': 'अनुपस्थिति अवधि',
    'Monthly Salary': 'मासिक वेतन',
    'Monthly Summary': 'मासिक सारांश',
    'Select Worker': 'कर्मचारी चुनें',
    'Select Paid Method': 'भुगतान विधि चुनें',
    'Cash': 'नकद',
    'Account': 'खाता',
    'Select Bore': 'बोर चुनें',
    'Select From and To Date': 'से और तक तिथि चुनें',
    'All days are present automatically. Select a date range only for absent days.': 'सभी दिन स्वचालित रूप से उपस्थित माने जाते हैं। केवल अनुपस्थित दिनों के लिए तिथि सीमा चुनें।',
    'Attendance': 'उपस्थिति',
    'All time': 'सभी समय',
    'Filter:': 'फ़िल्टर:',
    'Place': 'स्थान',
    'Diesel': 'डीज़ल',
    'Tyre': 'टायर',
    'Labour': 'श्रम',
    'Labour Payment': 'श्रम भुगतान',
    'Basic': 'बेसिक',
    'Premium': 'प्रीमियम',
    'Free': 'मुफ्त',
    'Subscribe': 'सब्सक्राइब करें',
    'Subscription': 'सदस्यता',
    'About Subscription': 'सदस्यता के बारे में',
    'Choose your plan': 'अपनी योजना चुनें',
    'Price per Manager': 'प्रति प्रबंधक मूल्य',
    'Managers Allowed': 'अनुमत प्रबंधक',
    'Managers': 'प्रबंधक',
    'Manager': 'प्रबंधक',
    'Owner': 'मालिक',
    'Owner Dashboard': 'मालिक डैशबोर्ड',
    'Edit Manager': 'प्रबंधक संपादित करें',
    'Delete Manager': 'प्रबंधक हटाएं',
    'Manager Usage': 'प्रबंधक उपयोग',
    'Live': 'लाइव',
    'Live Overview': 'लाइव अवलोकन',
    'Active': 'सक्रिय',
    'Frozen': 'फ़्रीज़',
    'Locked': 'लॉक',
    'Expired': 'समाप्त',
    'Not Set': 'सेट नहीं है',
    'Loading...': 'लोड हो रहा है...',
    'Loading manager...': 'प्रबंधक लोड हो रहा है...',
    'Loading manager data...': 'प्रबंधक डेटा लोड हो रहा है...',
    'AQUA TRACK': 'एक्वा ट्रैक',
    'BORE DRILLING MANAGEMENT': 'बोर ड्रिलिंग प्रबंधन',
    'Tap a manager to view details': 'विवरण देखने के लिए प्रबंधक को टैप करें',
    'Tap + to add your first manager': 'अपना पहला प्रबंधक जोड़ने के लिए + टैप करें',
    'Adjust': 'समायोजित करें',
    'Adjust Quantity': 'मात्रा समायोजित करें',
    'New Quantity': 'नई मात्रा',
    'Quantity': 'मात्रा',
    'Used': 'उपयोग किया गया',
    'Remaining': 'शेष',
    'Limit': 'सीमा',
    'Pipe': 'पाइप',
    'Pipe in Vehicle': 'वाहन में पाइप',
    'Pipe Size': 'पाइप आकार',
    'Pipes Used:': 'उपयोग किए गए पाइप:',
    'Feet Entries:': 'फुट प्रविष्टियां:',
    'Details': 'विवरण',
    'Edit Bore': 'बोर संपादित करें',
    'Select absent range': 'अनुपस्थिति सीमा चुनें',
    'Start Date': 'आरंभ तिथि',
    'End Date': 'समाप्ति तिथि',
    'Set Password': 'पासवर्ड सेट करें',
    'January': 'जनवरी',
    'February': 'फरवरी',
    'March': 'मार्च',
    'April': 'अप्रैल',
    'May': 'मई',
    'June': 'जून',
    'July': 'जुलाई',
    'August': 'अगस्त',
    'September': 'सितंबर',
    'October': 'अक्टूबर',
    'November': 'नवंबर',
    'December': 'दिसंबर',
  },
};

String tr(String key, String locale) {
  return _strings[locale]?[key] ?? key;
}
